version: "3.7"
services:
    web:
        container_name: nginx
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./sites:/etc/nginx/conf.d"
            - "./conf/nginx.conf:/etc/nginx/nginx.conf"
            - "./www:/var/www"
        links:
            - php
            - mariadb

    redis:
        container_name: redis
        image: redis:alpine  
        volumes:
            - "./conf/redis.conf:/etc/myredis.conf"
        ports:
            - "6379:6379"

    php:
        build: .
        working_dir: /var/www
        volumes:
            - "./www:/var/www"

    mariadb:
      container_name: mariadb
      image: mariadb
      ports:
          - "33061:33061"
          - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=password


    phpmyadmin:
      image: corbinu/docker-phpmyadmin
      links:
          - mariadb:mysql
      ports:
          - 8181:80
      environment:
          MYSQL_USERNAME: root
          MYSQL_ROOT_PASSWORD: password
          MYSQL_PORT_3306_TCP_ADDR: 0.0.0.0
    code:
        image: busybox
        volumes:
            - "./www:/var/www"

