version: "3.7"
services:
    web:
        container_name: nginx
        image: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./sites:/etc/nginx/conf.d"
            - "./conf/nginx.conf:/etc/nginx/nginx.conf"
            - "./www:/var/www"
        links:
            - php
            - mariadb

    redis:
        container_name: redis
        image: redis:alpine  
        volumes:
            - "./conf/redis.conf:/etc/myredis.conf"
        ports:
            - "6379:6379"

    php:
        build: .
        working_dir: /var/www
        volumes:
            - "./www:/var/www"

    mariadb:
      container_name: mariadb
      image: mariadb
      ports:
          - "33061:33061"
          - "3306:3306"
      environment:
        - MYSQL_ROOT_PASSWORD=password

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      depends_on:
          - mariadb
      ports:
          - 8080:80
      environment:
          - PMA_HOST=mariadb
      volumes:
          - /sessions
volumes:
   sessions
